### PR TITLE
Added my name to contributors.txt resubmitted

### PR DESCRIPTION
**Pull request by Debmallya-03**
Issue: #1 

Added my name to contributors.txt

### CODE REVIEW

**Comment by Debmallya-03** [comment]
I have registered both in unstop and geekhaven.

**Comment by aarav0180** [comment]
Hey @Debmallya-03 ! 👋

Hope you’re doing great! 😊 Just wanted to let you know that to ensure we can allocate the points correctly, you’ll need to submit the PR again for your contribution.

Don’t worry, it’s a simple process, and we really appreciate your effort! Let me know if you face any issues while creating the PR—I’m here to help.

Thanks a lot for your understanding! 🚀

**Pull request merged**
